insert into permissions (key, description)
values
  ('organization.read', 'Read organization details'),
  ('organization.update', 'Update organization details'),
  ('location.read', 'Read locations'),
  ('location.create', 'Create locations'),
  ('location.update', 'Update locations'),
  ('location.delete', 'Deactivate locations'),
  ('employee.read', 'Read organization employees'),
  ('employee.invite', 'Invite organization employees'),
  ('employee.update', 'Update organization employees'),
  ('employee.remove', 'Remove organization employees'),
  ('role.read', 'Read roles and permissions'),
  ('role.manage', 'Manage roles and permissions'),
  ('product.read', 'Read products'),
  ('product.create', 'Create products'),
  ('product.update', 'Update products'),
  ('product.delete', 'Deactivate products'),
  ('price.read', 'Read prices'),
  ('price.manage', 'Manage prices'),
  ('supplier.read', 'Read suppliers'),
  ('supplier.create', 'Create suppliers'),
  ('supplier.update', 'Update suppliers'),
  ('supplier.delete', 'Deactivate suppliers'),
  ('inventory.read', 'Read inventory'),
  ('inventory.adjust', 'Adjust inventory'),
  ('inventory.count', 'Perform inventory counts'),
  ('inventory.allow_negative_stock', 'Allow negative inventory'),
  ('purchase.read', 'Read purchases'),
  ('purchase.create', 'Create purchases'),
  ('purchase.confirm', 'Confirm purchases'),
  ('purchase.cancel', 'Cancel purchases'),
  ('purchase.void', 'Void purchases'),
  ('transfer.read', 'Read transfers'),
  ('transfer.create', 'Create transfers'),
  ('transfer.send', 'Send transfers'),
  ('transfer.receive', 'Receive transfers'),
  ('transfer.cancel', 'Cancel transfers'),
  ('transfer.void', 'Void transfers'),
  ('transformation.read', 'Read transformations'),
  ('transformation.create', 'Create transformations'),
  ('transformation.confirm', 'Confirm transformations'),
  ('transformation.cancel', 'Cancel transformations'),
  ('cash.read', 'Read cash sessions'),
  ('cash.open', 'Open cash sessions'),
  ('cash.close', 'Close cash sessions'),
  ('cash.reopen', 'Reopen cash sessions'),
  ('cash.expense.create', 'Create cash expenses'),
  ('daily_closure.read', 'Read daily closures'),
  ('daily_closure.create', 'Create daily closures'),
  ('daily_closure.confirm', 'Confirm daily closures'),
  ('daily_closure.cancel', 'Cancel daily closures'),
  ('daily_closure.void', 'Void daily closures'),
  ('notification.read', 'Read notifications'),
  ('notification.manage_preferences', 'Manage notification preferences')
on conflict (key) do update
set description = excluded.description;
